blank_issues_enabled: false

contact_links:
  - name: 💬 Forum
    url: https://github.com/vbti-development/onedl-mmengine/discussions
    about: Ask general usage questions and discuss with other OneDL-MMEngine community members
  - name: OneDL-MMEngine Documentation
    url: https://onedl-mmengine.readthedocs.io/en/latest/
    about: Check if your question is answered in docs
